-- 1. Create Cafes table
create table if not exists cafes (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  owner_id uuid references auth.users(id), -- Optional: Link to Supabase Auth user
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add cafe_id to existing tables
alter table products 
add column if not exists cafe_id bigint references cafes(id);

alter table tables 
add column if not exists cafe_id bigint references cafes(id);

alter table orders 
add column if not exists cafe_id bigint references cafes(id);

-- Note: order_items doesn't need cafe_id as it links to orders

-- 3. Seed Example Data (3 Cafes)
insert into cafes (name, slug) values 
  ('Merkez Kafe', 'merkez-kafe'),
  ('Sahil Kafe', 'sahil-kafe'),
  ('Kampüs Kafe', 'kampus-kafe')
on conflict (slug) do nothing;

-- 4. Seed Tables for each Cafe (Example: 5 tables each)
-- Merkez Kafe (ID likely 1)
insert into tables (name, status, cafe_id) values
  ('Masa 1', 'empty', (select id from cafes where slug='merkez-kafe')),
  ('Masa 2', 'empty', (select id from cafes where slug='merkez-kafe')),
  ('Masa 3', 'empty', (select id from cafes where slug='merkez-kafe'))
on conflict do nothing; -- Simplification, ideally checks constraint

-- Sahil Kafe (ID likely 2)
insert into tables (name, status, cafe_id) values
  ('Teras 1', 'empty', (select id from cafes where slug='sahil-kafe')),
  ('Teras 2', 'empty', (select id from cafes where slug='sahil-kafe'))
on conflict do nothing;

-- Kampüs Kafe (ID likely 3)
insert into tables (name, status, cafe_id) values
  ('Kutuphane Yanı', 'empty', (select id from cafes where slug='kampus-kafe')),
  ('Bahçe 1', 'empty', (select id from cafes where slug='kampus-kafe'))
on conflict do nothing;

-- 5. Seed Products for each Cafe
-- Merkez Kafe
insert into products (name, category, price, description, cafe_id) values
  ('Çay', 'İçecekler', 15, 'Taze demlenmiş çay', (select id from cafes where slug='merkez-kafe')),
  ('Türk Kahvesi', 'İçecekler', 40, 'Közde kahve', (select id from cafes where slug='merkez-kafe')),
  ('Tost', 'Yiyecekler', 60, 'Kaşarlı tost', (select id from cafes where slug='merkez-kafe'));

-- Sahil Kafe (Higher prices example)
insert into products (name, category, price, description, cafe_id) values
  ('Limonata', 'İçecekler', 50, 'Ev yapımı limonata', (select id from cafes where slug='sahil-kafe')),
  ('Hamburger', 'Yiyecekler', 150, 'Sahil burger', (select id from cafes where slug='sahil-kafe'));

-- Kampüs Kafe (Student friendly)
insert into products (name, category, price, description, cafe_id) values
  ('Filtre Kahve', 'İçecekler', 25, 'Sabah kahvesi', (select id from cafes where slug='kampus-kafe')),
  ('Sandviç', 'Yiyecekler', 40, 'Soğuk sandviç', (select id from cafes where slug='kampus-kafe'));

-- 6. Important: Enable RLS or update queries
-- For now, allow public access but ideally lock down by cafe_id
