-- 1. Ürünler Tablosu
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Masalar Tablosu
create table if not exists tables (
  id bigint generated by default as identity primary key,
  name text not null,
  status text default 'empty'
);

-- İlk 3 masayı oluştur (Varsa eklemez)
insert into tables (id, name, status)
values 
  (1, 'Masa 1', 'empty'),
  (2, 'Masa 2', 'empty'),
  (3, 'Masa 3', 'empty')
on conflict (id) do nothing;

-- 3. Siparişler (Ana Tablo)
create table if not exists orders (
  id bigint generated by default as identity primary key,
  table_id bigint references tables(id),
  status text default 'pending', -- 'pending' | 'prepared' | 'delivered'
  is_paid boolean default false,
  total_amount numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Sipariş Detayları (Ürünler)
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id),
  product_id bigint references products(id),
  name text not null,
  price numeric not null,
  quantity integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Realtime Yayınlarını Aç (Anlık bildirimler için ŞART)
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table tables, orders, order_items;
commit;
